### ISSUE TITLE
Using terminal-notifier OS X for a GUIless version

### ISSUE THREAD

**Issue by ahmetb** [gawen/hnotify#4]
Stuff like pyqt comes with lots of dependencies and might mess things up.

I'd prefer a command line version of this project, that only pushes me notifications when I'm using my computer, instead of using a space on my notification bar.

http://osxdaily.com/2012/08/03/send-an-alert-to-notification-center-from-the-command-line-in-os-x/ This one should help for OS X. I'd support the idea of making a gui-less version of this.

**Comment by sindresorhus** [comment]
:+1:
